blueprint:
  name: Light Controls AL v1.3
  description: "
    DIY Adaptive Lighting but with individual bulb support.

    ## New in version 1.3

    - Added light sync support to auto adjust lights out of sync when turning on (requires a new helper input).
    "
  domain: automation
  author: "Samuel Coles"
  homeassistant:
    min_version: 2024.5.3

  # Inputs
  input:
    room_identifier:
      name: Room Identifier
      description: "I.e., kitchen. Used as part of scene/script names, i.e., scene.kitchen_concentrate_lights. Case sensitive."
      selector:
        text:

    light_group:
      name: Light Group
      description: The light group to detect state changes. I.e., light.kitchen.
      selector:
        entity:
          domain:
            - light
            - group

    light_entities:
      name: Light Entities
      description: "The individual light entities that make up a group. I.e., light.kitchen_ceiling_1."
      selector:
        entity:
          domain: light
          multiple: true

    hue_button_2_entity_id:
      name: Hue Button 2 Entity ID
      description: "Hue button 2 on the Hue Dimmer Switch 2."
      selector:
        entity:
          domain: event

    hue_button_3_entity_id:
      name: Hue Button 3 Entity ID
      description: "Hue button 3 on the Hue Dimmer Switch 2."
      selector:
        entity:
          domain: event

    hue_button_4_entity_id:
      name: Hue Button 4 Entity ID
      description: "Hue button 4 on the Hue Dimmer Switch 2."
      selector:
        entity:
          domain: event

    time_based_transition:
      name: Transition Time
      description: "The time (in seconds) it takes to transition from one scene to another when triggered by time."
      selector:
        number:
          max: 1800
          min: 0
      default: 60

    hue_double_press_action:
      name: "Double-Press Action (Hue)"
      description: "Action that triggers when the hue button is double-pressed. Can be a scene or script."
      selector:
        entity:
          domain:
            - scene
            - script
      default: none

    light_override_switch:
      name: "AL Override Switch"
      description: "Stops all adaptive lighting."
      selector:
        entity:
          domain: input_boolean

    transition_helper:
      name: "Transitioning Helper"
      description: "Helper to track transitioning state."
      selector:
        entity:
          domain: input_boolean

    manual_adjustment_detector:
      name: "Manual Adjustment Detector"
      description: "Provide a template sensor which outputs either 'manual' or 'auto'."
      selector:
        entity:
          domain: sensor

    manual_adjustment_timeout:
      name: "Manual Adjustment Timeout"
      description: "Time in seconds before manual mode resets to auto mode."
      selector:
        number:
          min: 5
          max: 3600
          step: 5
      default: 15

    light_sync:
      name: "Light Sync"
      description: "Helper to track the sync-state of all lights in a group."
      selector:
        entity:
          domain: input_boolean

# Triggers
trigger:
  - id: light_group_turns_on
    platform: state
    entity_id: !input light_group
    to: "on"
    from: "off"

  - id: light_group_turns_off
    platform: state
    entity_id: !input light_group
    to: "off"
    from: "on"

  - id: individual_light_turns_on
    platform: state
    entity_id: !input light_entities
    to: "on"
    from: "off"
    for:
      seconds: 3

  - id: individual_light_turns_off
    platform: state
    entity_id: !input light_entities
    to: "off"
    from: "on"
    for:
      seconds: 3

  - id: brightness_up_button_short_release
    platform: state
    entity_id: !input hue_button_2_entity_id
    attribute: event_type
    to: short_release

  - id: brightness_down_button_short_release
    platform: state
    entity_id: !input hue_button_3_entity_id
    attribute: event_type
    to: short_release

  - id: hue_button_long_press
    platform: state
    entity_id: !input hue_button_4_entity_id
    attribute: event_type
    to: long_press

  - id: hue_button_short_release
    platform: state
    entity_id: !input hue_button_4_entity_id
    attribute: event_type
    to: short_release

  - id: light_control_config_updates
    platform: state
    entity_id: sensor.light_control_config

  - id: manual_mode_detected
    platform: state
    entity_id: !input manual_adjustment_detector
    to: manual
    for:
      seconds: !input manual_adjustment_timeout

  - id: auto_mode_detected
    platform: state
    entity_id: !input manual_adjustment_detector
    to: auto
    for:
      seconds: 15

# Variables
variables:
  # Inputs
  room_identifier: !input room_identifier
  light_group: !input light_group
  light_entities: !input light_entities
  time_based_transition: !input time_based_transition
  hue_double_press_action: !input hue_double_press_action
  light_override_switch: !input light_override_switch
  transition_helper: !input transition_helper
  light_sync: !input light_sync

  # Helpers
  light_override_is_active: >
    {{ is_state(light_override_switch, 'on') }}
  scene_data: >
    {{ (states('sensor.light_control_config') | from_json | default({})) }}
  scene_data_primary: >
    {{ scene_data['primary'] }}
  scene_data_secondary: >
    {{ scene_data['secondary'] }}
  scene_data_active_time_block: >
    {{ scene_data['time'] }}
  hue_double_press_prefix: >
    {{ hue_double_press_action.split('.')[0] }}
  is_transitioning: >
    {{ is_state(transition_helper, 'on') }}
  light_sync_is_armed: >
    {{ is_state(light_sync, 'on') }}

# Conditions
condition: []

# Actions
action:
  - choose:
      # Lights turn on from off state:
      # - Set kelvin and brightness
      # - Turn off light sync (if on)
      - conditions:
          - condition: trigger
            id: light_group_turns_on
          - condition: template
            value_template: "{{ not light_override_is_active }}"
        sequence:
          - service: hue.activate_scene
            metadata: {}
            data:
              transition: 1
            target:
              entity_id: scene.{{ room_identifier }}_{{ scene_data_primary['scene'] }}

      # Lights turn off:
      # - Reset light override switch
      # - Turn off transitioning helper
      # - Turn off light sync
      - conditions:
          - condition: trigger
            id: light_group_turns_off
        sequence:
          - if:
              - condition: template
                value_template: "{{ light_override_is_active }}"
            then:
              - service: input_boolean.turn_off
                target:
                  entity_id: "{{ light_override_switch }}"
          - if:
              - condition: template
                value_template: "{{ is_transitioning }}"
            then:
              - service: input_boolean.turn_off
                target:
                  entity_id: "{{ transition_helper }}"
          - if:
              - condition: template
                value_template: "{{ light_sync_is_armed }}"
            then:
              - service: input_boolean.turn_off
                target:
                  entity_id: "{{ light_sync }}"

      # Individual lights turn off:
      # - Arm light sync if light group is still on
      - conditions:
          - condition: trigger
            id: individual_light_turns_off
          - condition: template
            value_template: "{{ not light_sync_is_armed }}"
          - condition: template
            value_template: "{{ is_state(light_group, 'on') }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ light_sync }}"

      # Individual lights turning on
      # - Sync light entity if light sync is armed
      # - Turn off light sync after delay
      - conditions:
          - condition: trigger
            id: individual_light_turns_on
          - condition: template
            value_template: "{{ light_sync_is_armed }}"
        sequence:
          - variables:
              active_light: "{{ trigger.entity_id }}"
              active_light_attrs: "{{ states[active_light].attributes | tojson | from_json }}"
              reference_light: >
                {% set active_lights = (
                  states.light
                  | selectattr('state', 'eq', 'on')
                  | selectattr('entity_id', 'in', light_entities)
                  | sort(attribute='last_updated', reverse=False)
                ) %}
                {{ active_lights | map(attribute='entity_id') | list | first or None }}
              reference_light_attrs: "{{ states[reference_light].attributes | tojson | from_json if reference_light is not none else {} }}"
          - if:
              - condition: template
                value_template: "{{ reference_light is not none }}"
            then:
              - variables:
                  active_brightness: "{{ active_light_attrs['brightness'] | default(0) }}"
                  reference_brightness: "{{ reference_light_attrs['brightness'] | default(0) }}"
              - if:
                  - condition: template
                    value_template: >
                      {{
                        active_brightness != reference_brightness or
                        active_light_attrs['color_temp_kelvin'] != reference_light_attrs['color_temp_kelvin']
                      }}
                then:
                  - service: light.turn_on
                    data:
                      transition: 1
                      brightness: "{{ reference_brightness }}"
                      kelvin: "{{ reference_light_attrs['color_temp_kelvin'] }}"
                    target:
                      entity_id: >
                        {% set active_lights = (
                          states.light
                          | selectattr('state', 'eq', 'on')
                          | selectattr('entity_id', 'in', light_entities)
                          | list
                        ) %}
                        {{ active_lights | map(attribute='entity_id') | list }}
                  - delay:
                      seconds: 5
                  - if:
                      - condition: template
                        value_template: >
                          {% set active_lights = (
                            states.light
                            | selectattr('state', 'eq', 'off')
                            | selectattr('entity_id', 'in', light_entities)
                            | list
                          ) %}
                          {{ active_lights | map(attribute='entity_id') | list | length == 0 }}
                    then:
                      - service: input_boolean.turn_off
                        target:
                          entity_id: "{{ light_sync }}"

      # Brightness up/down turns on light override switch.
      - conditions:
          - condition: trigger
            id:
              - brightness_up_button_short_release
              - brightness_down_button_short_release
          - condition: template
            value_template: "{{ not light_override_is_active }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ light_override_switch }}"

      # Long hue press detected:
      # - Set lights to default state
      # - Turn off light override switch
      - conditions:
          - condition: trigger
            id: hue_button_long_press
        sequence:
          - service: hue.activate_scene
            metadata: {}
            data:
              transition: 1
            target:
              entity_id: scene.{{ room_identifier }}_{{ scene_data_primary['scene'] }}
          - if:
              - condition: template
                value_template: "{{ light_override_is_active }}"
            then:
              - service: input_boolean.turn_off
                target:
                  entity_id: "{{ light_override_switch }}"

      # Single or double-press (hue) detected:
      # - Set an alternative scene or script
      # - Turn on light override switch
      - conditions:
          - condition: trigger
            id: hue_button_short_release
        sequence:
          - if:
              - condition: template
                value_template: "{{ not light_override_is_active }}"
            then:
              - service: input_boolean.turn_on
                target:
                  entity_id: "{{ light_override_switch }}"
          - wait_for_trigger:
              - platform: state
                entity_id: !input hue_button_4_entity_id
                attribute: event_type
                to: short_release
            timeout: "0.5"
          - choose:
              # Double-press action
              - conditions:
                  - condition: template
                    value_template: >
                      {{ wait.trigger is not none and hue_double_press_action != 'none' }}
                sequence:
                  - service: "{{ hue_double_press_prefix }}.turn_on"
                    target:
                      entity_id: "{{ hue_double_press_action }}"
              # Single-press action
              - conditions:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}"
                sequence:
                  - service: hue.activate_scene
                    metadata: {}
                    data:
                      transition: 1
                    target:
                      entity_id:
                        - scene.{{ room_identifier }}_{{ scene_data_secondary['scene'] }}

      # Transition lights based on time of day (when light_control_config updates).
      - conditions:
          - condition: trigger
            id: light_control_config_updates
          - condition: template
            value_template: >
              {% set current_time = now().strftime('%H:%M') %}
              {{ scene_data_active_time_block == current_time }}
          - condition: template
            value_template: "{{ not light_override_is_active }}"
        sequence:
          - if:
              - condition: state
                entity_id: !input light_group
                state: "on"
            then:
              - service: input_boolean.turn_on
                target:
                  entity_id: "{{ transition_helper }}"
              - if:
                  - condition: template
                    value_template: >-
                      {{
                        light_entities
                        | select('in', (
                            states.light
                            | selectattr('state', 'eq', 'off')
                            | map(attribute='entity_id')
                            | list
                        ))
                        | list
                        | length > 0
                      }}
                then:
                  - variables:
                      active_lights: >
                        {{
                          light_entities
                          | select('in',
                              states.light
                              | selectattr('state', 'eq', 'on')
                              | map(attribute='entity_id')
                              | list
                          )
                          | list
                        }}
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ active_lights | length > 0 }}"
                        sequence:
                          - service: light.turn_on
                            data:
                              transition: "{{ time_based_transition }}"
                              brightness: "{{ scene_data_primary['brightness'] }}"
                              kelvin: "{{ scene_data_primary['kelvin'] }}"
                            target:
                              entity_id: "{{ active_lights }}"
                else:
                  - service: hue.activate_scene
                    metadata: {}
                    data:
                      transition: "{{ time_based_transition }}"
                    target:
                      entity_id: scene.{{ room_identifier }}_{{ scene_data_primary['scene'] }}
              - delay: "{{ time_based_transition }}"
              - service: input_boolean.turn_off
                target:
                  entity_id: "{{ transition_helper }}"

      # Set override switch when manual mode detected.
      - conditions:
          - condition: trigger
            id: manual_mode_detected
          - condition: template
            value_template: "{{ not light_override_is_active }}"
          - condition: template
            value_template: "{{ not is_transitioning }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ light_override_switch }}"

      # Turn off override switch when auto mode detected.
      - conditions:
          - condition: trigger
            id: auto_mode_detected
          - condition: template
            value_template: "{{ light_override_is_active }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ light_override_switch }}"

mode: single
